### ISSUE TITLE
Screen Recording detected

### ISSUE THREAD

**Issue by 420Dope** [EamonTracey/SecretShot#6]
Snapchat detect screen recording in my chat. Or I am the only one how see it in my chat and the other person don't see it?
Or maybe because I use Choicy to disable tweaks in Snapchat? Or it is a conflict with Snapper 2?

iPhone X iOS 14.3 unc0ver
Snapchat Version: 11.71.0.35

**Comment by 420Dope** [comment]
Solved.
I have to whitelist SecretShot in Snapchat App with Choicy.

**Comment by realbillie** [comment]
Thankyou! This just helped me too!
